"""Build complete, non-overlapping Shanggu Sans webfont chunks."""

from __future__ import annotations

import argparse
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


VERSION = "shanggu-web-v4"
WEIGHTS = (("Regular", 400), ("Bold", 700))
CHUNK_RANGES = (
    ("symbols", 0x0000, 0x33FF),
    ("cjk-ext-a", 0x3400, 0x4DBF),
    ("cjk-1", 0x4E00, 0x62FF),
    ("cjk-2", 0x6300, 0x77FF),
    ("cjk-3", 0x7800, 0x8CFF),
    ("cjk-4", 0x8D00, 0x9FFF),
    ("yi", 0xA000, 0xAFFF),
    ("pua-1", 0xB000, 0xBFFF),
    ("pua-2", 0xC000, 0xCFFF),
    ("bmp-tail", 0xD000, 0xFFFF),
    ("supplementary", 0x10000, 0x10FFFF),
)


def cmap(path: Path) -> set[int]:
    with TTFont(path) as font:
        return set().union(*(table.cmap for table in font["cmap"].tables))


def page_characters(project_root: Path) -> set[int]:
    sources = list(project_root.glob("*.html"))
    sources.extend((project_root / "converter").glob("*.html"))
    sources.extend((project_root / "converter").glob("*.js"))
    sources.extend((project_root / "ghc-comparison").glob("*.html"))
    text = "".join(path.read_text(encoding="utf-8") for path in sources)
    # Keep all characters that can occur in the UI or converter messages. The
    # Latin glyphs cost little and make the core independently usable.
    return {ord(character) for character in text}


def unicode_range(
    codepoints: set[int], blockers: set[int] | None = None, max_gap: int = 0
) -> str:
    ordered = sorted(codepoints)
    if not ordered:
        return ""
    intervals: list[tuple[int, int]] = []
    start = previous = ordered[0]
    blockers = blockers or set()
    for codepoint in ordered[1:]:
        gap_has_blocker = any(previous < blocker < codepoint for blocker in blockers)
        if codepoint - previous <= max_gap + 1 and not gap_has_blocker:
            previous = codepoint
            continue
        intervals.append((start, previous))
        start = previous = codepoint
    intervals.append((start, previous))
    return ", ".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in intervals
    )


def write_subset(source: Path, output: Path, codepoints: set[int]) -> None:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_legacy = True
    options.name_languages = ["*"]
    options.recommended_glyphs = True
    options.notdef_glyph = True
    options.notdef_outline = True
    font = subset.load_font(str(source), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    subset.save_font(font, str(output), options)


def build(source_root: Path, project_root: Path) -> None:
    output_root = project_root / "fonts" / "shanggu-web"
    output_root.mkdir(parents=True, exist_ok=True)
    for old_font in output_root.glob("*.woff2"):
        old_font.unlink()

    core_source = page_characters(project_root)
    css = ["/* Generated by scripts/build-shanggu-webfonts.py. */"]
    generated = 0

    for style, weight in WEIGHTS:
        source = source_root / f"ShangguSans-{style}.ttf"
        source_cmap = cmap(source)
        core = source_cmap & core_source
        groups: list[tuple[str, set[int], bool]] = [("core", core, True)]
        covered = set(core)
        for name, first, last in CHUNK_RANGES:
            points = {cp for cp in source_cmap - core if first <= cp <= last}
            if points:
                groups.append((name, points, False))
                covered.update(points)
        if covered != source_cmap:
            missing = sorted(source_cmap - covered)
            raise RuntimeError(f"Chunk plan misses U+{missing[0]:04X}")

        for name, points, is_core in groups:
            filename = f"ShangguSans-{style}-{name}.woff2"
            write_subset(source, output_root / filename, points)
            css.extend(
                (
                    "@font-face {",
                    '  font-family: "Shanggu Web";',
                    f'  src: url("shanggu-web/{filename}?v={VERSION}") format("woff2");',
                    f"  font-weight: {weight};",
                    "  font-style: normal;",
                    "  font-display: swap;",
                    f"  unicode-range: {unicode_range(points, core, 0 if is_core else 255)};",
                    "}",
                )
            )
            generated += 1

    (project_root / "fonts" / "shanggu-web.css").write_text(
        "\n".join(css) + "\n", encoding="utf-8"
    )
    print(f"Generated {generated} Shanggu webfont subsets in {output_root}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source_root", type=Path)
    parser.add_argument("project_root", type=Path)
    arguments = parser.parse_args()
    build(arguments.source_root.resolve(), arguments.project_root.resolve())
